### PR TITLE
Remove FT Politics from UK / UK Politics streams

### PR DESCRIPTION
**Pull request by mmockett**
And add it to World.

@i-like-robots do you need to reingest this for it to appear? Think you did last time.

### CODE REVIEW

**Comment by i-like-robots** [comment]
Yep

**Comment by i-like-robots** [comment]
(this required a re-deploy of es-interface to pull in the latest version of this module)

**Comment by mmockett** [comment]
Ah... is that a big bit of work?

**Comment by i-like-robots** [comment]
not at all, just not going to deploy it at this time on a Friday =]

**Comment by i-like-robots** [comment]
Podcasts have been reingested

**Comment by mmockett** [comment]
You da best, mayne

**Pull request merged**
